---

- name: Forget previouly known keys for this host

  delegate_to: localhost

  command: ssh-keygen -R {{ vm_hostname }}.{{ network_name }}

- name: Forget previouly known keys for this host on bastion too

  delegate_to: '{{ hostvars[bastion].ansible_host }}'

  command: ssh-keygen -R {{ vm_hostname }}.{{ network_name }}
