---

- name: Power on VM

  delegate_to: '{{ pysphere }}'
  register: boot_
  no_log: True

  vsphere_guest:
    validate_certs: '{{ validate_certs }}'
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"
    state: powered_on
