---

- name: Power on VM

  delegate_to: pysphere
  register: boot_

  vsphere_guest:
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"
    state: powered_on
