---

- name: Clone VM

  register: clone_
  delegate_to: '{{ pysphere }}'
  no_log: True

  vsphere_guest:
    validate_certs: '{{ validate_certs }}'
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"
    from_template: yes
    template_src: "{{ template_name }}"
    cluster: "{{ cluster }}"
    resource_pool: "{{ resource_pool }}"
