---

- name: Register VM facts

  when: not clone_|skipped
  register: vm_
  check_mode: False
  delegate_to: pysphere

  vsphere_guest:
    validate_certs: '{{ validate_certs }}'
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"
    vmware_guest_facts: yes

- debug: { var: vm_ }
  when: debug is defined and not clone_|skipped
