---

- name: Restart VM

  delegate_to: pysphere
  register: restart_

  vsphere_guest:
    validate_certs: '{{ validate_certs }}'
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"
    state: restarted

- name: Wait for ssh to appears

  when: boot_.changed
  delegate_to: vbastion

  wait_for:
    host: "{{ vm_hostname }}.{{ network_name }}"
    port: 22
    delay: 20
    timeout: 30
