---

- name: power off VM

  when: clone_.changed or shutdown|default(False)
  register: shutdown_
  delegate_to: '{{ pysphere }}'
  no_log: True

  vsphere_guest:
    validate_certs: '{{ validate_certs }}'
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"
    state: powered_off
