---

- name: Get VM status

  delegate_to: '{{ pysphere }}'
  register: status_
  check_mode: False
  when: (clone_ is defined and not clone_|skipped) or clone_ is not defined
  no_log: True

  vsphere_status:
    validate_certs: '{{ validate_certs }}'
    vcenter_hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    guest: "{{ vm_name }}"

- name: Set VM status fact

  check_mode: False
  when: not status_|skipped

  set_fact: { vm_status: "{{ status_.status }}" }
