---

- name: restart dhcpd

  delegate_to: '{{ dhcpd }}'
  # https://github.com/ansible/ansible/issues/17490
  become: True

  service:
    name: "{{ dhcpd_service }}"
    state: restarted

- name: restart sshd

  become: True

  service:
    name: ssh
    state: restarted
